name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------------
      # Checkout
      # ---------------------------------------------------------------

      # Checkout the code so it is available locally on the GitHub
      # runner.

      - name: Checkout your repository using git
        uses: actions/checkout@v4

      # ---------------------------------------------------------------
      # Build
      # ---------------------------------------------------------------

      # Build documentation site

      - name: Build
        uses: withastro/action@v2

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}

    steps:
      # ---------------------------------------------------------------
      # Publish
      # ---------------------------------------------------------------

      # Publish documentation site

      - name: Publish to GitHub Pages
        id: publish
        uses: actions/deploy-pages@v4
